sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
env:
  matrix:
    - DJANGO_MAX=2.2.100 DB=postgres TEST=pulp
    - DJANGO_MAX=2.2.100 TEST=docs
matrix:
  fast_finish: true
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: '9.6'
services:
  - postgresql
  - redis-server
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: .travis/script.sh
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: pulp
        password:
          secure: "EerGV8Z0jybfuq2yHWrD2fu6NnZxLBjAz/kyhGGuXOcSCkBsWfrDoatszMhKtBR7A4o+xzUo/OsRV2rILz3IWPg0aOBk3GAAH0dg6axt25JrJbnd8+lCj4XTyhg0dR/J/EsE0S8xGV6mG6Z+ubRvBRtc1pGdQvq2PxuQcPISi35zNhwqUoNIJ8f1NDa7Rl/7jyhM/YIlrfH2gtRaIDIhrHHeXqm9JIHCPRpyx//t1BKDov3TrPeiohmu/OvwNS3F4a/Juxscl9sAm4JeduJA5N6nYkjlCsYYe7L54kluXIN0bCcKv0qKNDbf/EfTP3/SHzywkJwr5IFlRsf2rNiOiBrec03Xhh10JbIhyFMyI2BqDHSghfxG8D3m4EFtwebowgXixCBBRDyIRxiK+NEt4DxVahwV4gZiYZzG0h7TqL2/zmgTL4Tj09iqKbfLtzccmVLsGikHWCQxctefHCyD6oN/TWRSay0fLZGIyCL0YwQOTyS6IzfBYlwxDtke92okHrH2bASVBczAZcOMUOcbxxYVrL2XWQI8XIjguOBlxbv80GM1ZXC+rEvZ9WOSLBv9QJAC1V+cYfWAjCQ3jpmzz2TSIx4HH7l1wt5fBOMnnWDB+gKfqLlOpMrAnqkbR/YiyXkL0wBtAOW7ZTS0iDARgJpKT3V/dvyqXYwEmWfDJB4="
        on:
          tags: true
      if: tag IS present
    - stage: publish-beta-docs
      script: bash .travis/publish_docs.sh beta
      env:
        - DJANGO_MAX=2.2.100
        - DB=postgres
        - TEST=docs
      if: tag IS present
    - stage: publish-nightly-docs
      script: bash .travis/publish_docs.sh nightly
      env:
        - DJANGO_MAX=2.2.100
        - DB=postgres
        - TEST=docs
      if: type != pull_request
