---
- hosts: localhost
  gather_facts: false
  vars:
    container_cli: 'docker'
  vars_files:
    - vars/defaults.yaml
  tasks:
    - import_tasks: common_tasks.yaml

    - name: 'Build images'
      command: "{{ container_cli }} build --network host --no-cache --build-arg VERSION={{ item.value.tag }} --build-arg PULPCORE={{ item.value.pulpcore | default('pulpcore') }} --build-arg PULPCORE_PLUGIN={{ item.value.pulpcore_plugin | default('pulpcore-plugin') }} --build-arg PLUGINS=\"{{ item.value.plugins | default([]) | join(' ') }}\" -t {{ item.value.image_name }}:{{ item.value.tag }} ."
      args:
        chdir: images/pulp
      with_dict: "{{ images }}"

    - name: 'Tag images'
      command: "{{ container_cli }} tag {{ item.value.image_name }}:{{ item.value.tag }} {{ registry }}/{{ project }}/{{ item.value.image_name }}:{{ item.value.tag }}"
      with_dict: "{{ images }}"
