---
- hosts: localhost
  gather_facts: false
  vars:
    container_cli: 'docker'
  vars_files:
    - vars/defaults.yaml
  tasks:
    - name: 'Check for podman'
      command: 'which podman'
      register: podman_exists
      ignore_errors: true

    - set_fact:
        container_cli: 'podman'
      when: podman_exists | success

    - name: 'Build images'
      command: "{{ container_cli }} build --network host --no-cache --build-arg VERSION={{ tag }} --build-arg PLUGINS=\"{{ item.value.plugins | join(' ') }}\" -t {{ item.key }}:{{ tag }} ."
      args:
        chdir: images/pulp
      with_dict: "{{ images }}"

    - name: 'Tag images'
      command: "{{ container_cli }} tag {{ item.key }}:{{ tag }} {{ registry }}/{{ project }}/{{ item.key }}:{{ tag }}"
      with_dict: "{{ images }}"
