---
- hosts: localhost
  gather_facts: false
  vars:
    container_cli: 'docker'
  vars_files:
    - vars/defaults.yaml
  tasks:
    - import_tasks: common_tasks.yaml

    - name: Generate per-image Dockerfiles from the Dockerfile template
      template:
        src: images/pulp/Dockerfile.j2
        dest: "images/pulp/Dockerfile.{{ item.key }}"
      with_dict: "{{ images }}"

    - name: 'Build images'
      # We build from the ../.. (parent dir of pulpcore git repo) Docker build
      # "context" so that repos like pulpcore-plugin are accessible to Docker
      # build. So that PR branches can be used via relative paths.
      command: "{{ container_cli }} build --network host --no-cache -t {{ item.value.image_name }}:{{ item.value.tag }} -f images/pulp/Dockerfile.{{ item.key }} ../.."
      with_dict: "{{ images }}"

    - name: 'Tag images'
      command: "{{ container_cli }} tag {{ item.value.image_name }}:{{ item.value.tag }} {{ registry }}/{{ project }}/{{ item.value.image_name }}:{{ item.value.tag }}"
      with_dict: "{{ images }}"
